### PR TITLE
add multiple shim servers support

### LINKED ISSUE #2: Support multiple shim servers
This is needed in order to implement other renderers that are not written in Python, like Asciidoctor.

### PR DESCRIPTION
**Pull request by miltador**
Closes #2

Supersedes #1

### CODE REVIEW

**Comment by tychoish** [comment]
Hrm, sorry I tried to fix the merge conflict due to merging your other pull requests, but I seem to have bungled it. Sorry, I'm a bit new to some of these features :)

I wanted to poke around this change, and did some refactoring that I thought might be interesting to consider. Tell me what you think

**Comment by tychoish** [comment]
I opened pull request #6 with a little bit of refactoring. I'll either merge that your you can merge it into this and continue to refactor if there's more you'd like to change, and I'd be happy to merge that.

**Comment by tychoish** [comment]
Let me know if you have any questions, and I'm sorry for the bad form of the second pull request. I like the idea that you're going with, I  definitely want to provide support for as many formats as possible, as I think the slow build times that shelling out for every page doesn't do anyone any good.

**Comment by miltador** [comment]
I'll provide my feedback probably later today when I have some spare time. From a quick lookup - looks good, I like your improvements but there are some points to discuss. Thank you!

**Comment by miltador** [comment]
Feel free to merge #6 instead and thanks for looking into it!

**Pull request closed without merging**
